version: '3'
name: actcast_bot

services:
  bot:
    container_name: tg_actcast_bot
    restart: unless-stopped
    build: .
    env_file:
      - .env
    networks:
      - my_bridge

    volumes:
      - /data:/app/data

  admin_bot:
    container_name: tg_actcast_admin_bot
    restart: unless-stopped
    build: ./AdminPanel
    env_file:
      - .env
    networks:
      - my_bridge

  backup_bot:
    container_name: tg_actcast_backup_bot
    restart: unless-stopped
    build: ./Backup
    env_file:
      - .env
    networks:
      - my_bridge

  report_bot:
    container_name: tg_actcast_report_bot
    restart: unless-stopped
    build: ./Report
    env_file:
      - .env
    networks:
      - my_bridge

  report_survey_bot:
    container_name: tg_actcast_report_survey_bot
    restart: unless-stopped
    build: ./ReportSurvey
    env_file:
      - .env
    networks:
      - my_bridge

  mongodb:
    image: mongo:6.0
    container_name: tg_actcast_mongodb
    restart: unless-stopped
    ports:
      - "3003:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
      MONGO_INITDB_DATABASE: tg
    networks:
      - my_bridge

volumes:
  mongodb_data:


networks:
  my_bridge:
    driver: bridge
